sudo: required
dist: trusty
language: node_js
node_js: '8'
notifications:
  email: false

  stages:
  - name: Deploy release branch
script:
- echo "skipping tests"


branches:
  only:
  - master
  - /^deploy.*$/

jobs:
  fast_finish: true
  include:
    - stage: Deploy release branch
      
      deploy:
        - provider: script
          script: ./deploy-test.sh
          on:
            all_branches: true
            condition: $TRAVIS_BRANCH =~ ^deploy.*$
