sudo: required
dist: trusty
language: node_js
node_js: '8'
notifications:
  email: false

  stages:
  - name: Deploy release branch
script:
- echo "skipping tests"
- export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"

jobs:
  fast_finish: true
  include:
    - stage: Deploy release branch
      deploy:
        - provider: script
          script: ./deploy-test.sh
          on:
            all_branches: true
            condition: ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} =~ ^deploy\/.*$
