sudo: required
dist: trusty
language: node_js
node_js: '8'
notifications:
  email: false
git:
  submodules: false
stages:
  - name: Deploy release branch
script:
- echo "skipping tests"
branches:
  only:
  - /^(?i:deploy)-.*$/
jobs:
  fast_finish: true
  include:
    - stage: Deploy release branch
      if: branch = deploy-123-12   AND type = push
      deploy:
        - provider: script
          script: ./deploy-test.sh
          on:
            branch: deploy-123-12 
